[Features]
; Restore Minimap HUD and compass navigation in Survivor Mode (true / false)
EnableSurvivorMinimap = true

; Restore Minimap toggle option (ON / OFF) under OPTIONS -> INTERFACE (true / false)
EnableMinimapMenuToggle = true

; Unlock restricted Survivor Mode skills (including 'Show Plants' on minimap) (true / false)
UnlockSurvivorSkills = true

; Skip unskippable Ubisoft Logo and startup warning screens (Epilepsy & AutoSave) (true / false)
SkipIntroScreens = true

; Skip Far Cry Primal short logo movie on game boot (true / false)
SkipPrimalLogo = true
